### PR TITLE
testthat added

### PR DESCRIPTION
**Pull request by HJ08003**
(1) It has passed "R CMD check--as-cran" with no WARNINGS/NOTES.

* checking tests ...
  Running ‘testthat.R’ 
 [266s/266s]
 OK
* checking PDF version of manual ... OK
* DONE
Status: OK

(2) For win-builder, it is same as before: complaining about that not installed for 'arch = i386'

* loading checks for arch 'i386'
** checking whether the package can be loaded ... ERROR
Loading this package had a fatal error status code 1
Loading log:
Error: package 'eco' is not installed for 'arch = i386'
Execution halted
** DONE
Status: 1 ERROR, 1 NOTE

### CODE REVIEW

**Comment by HJ08003** [comment]
I fixed the memory errors in the C code which caused the crash in run-time on windows x86. 
Now it passed
(1) passed R CMD check --as-cran on MacOX (testthat ran as well)
(2) passed R CMD check --as-cran on Windows (testthat ran on both x86 and i386)
(3) passed travis-ci check

Win-builder is same as before, not installed for i386.

**Comment by kosukeimai** [comment]
I don't understand some of these changes.  What's `Free()`?  Shouldn't we be using `free()` when releasing the memory from `malloc()`?

**Comment by HJ08003** [comment]
The code used several ways to allocate memory for Array, Matrix and Matrix3D. Both malloc and Calloc used in the implementation. 

The malloc allocated memory needs to be release by free() and Calloc allocated memory needs to be released by Free(). For MacOS/Linux/i386, it is not a big deal when there are mismatches. But for x86, it caused the C code crashed.

**Comment by HJ08003** [comment]
@kosukeimai 
Yes, now I see what you meant. I did mixed free and Free in the function "FreeintMatrix". It did not cause a problem because "intMatrix" is never used in the code. I have corrected that in the revision few minutes ago.

**Comment by HJ08003** [comment]
Accuracy depends on long.double setting.

**Comment by HJ08003** [comment]
To make sure the test takes no more than 10s, I skip some of them in testthat. However, people can always add them back by setting the variable [donotrun = 1].

Now, it passed the check on Window, Mac and Linux, as well as travis-ci. It is ready to be merged.

**Comment by kosukeimai** [comment]
@HJ08003 I don't understand why you are using `Free()` instead of `free()`

**Comment by kosukeimai** [comment]
@HJ08003 Can you double-check `free()` vs. `Free()` issues?  Thanks.

**Comment by HJ08003** [comment]
Yes, here are matching pairs:
(1) memory allocated by malloc will be released by free
(2) memory allocated by Calloc will be released by Free
(3) memory allocated by doubleMatrix(row, col) will be released by FreeMatrix(M, row)
(4) memory allocated by doubleMatrix3D will be released by Free3DMatrix

Note:
doubleMatrix is implemented by two layers of Calloc, so the release in FreeMatrix needs to be two layers of Free
doubleMatrix3D is implemented by calloc and doubleMatrix, so the the release in Free3DMatrix should be FreeMatrix and free.

**Pull request merged**
